spring:
  h2:
    console:
      enabled: true
  datasource:
    platform: h2
    url: jdbc:h2:mem:testdb  # Use an in-memory H2 database
    username: sa
    password:
    driverClassName: org.h2.Driver
  allowed:
    resources: /h2-console/**

application:
  security:
    jwt:
      secret-key: 404E635266556A586E327AWSDD21282F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
